### ISSUE TITLE
Modelado 

### ISSUE THREAD

**Issue by jairomelo** [Cibercliografia/Corpus-de-derecho-castellano-indiano-digital#3]
He realizado un primer prototipo de modelado usando como ejemplo las glosas de Gregorio López a las Siete Partidas de Alonso Nono (sic), edición de 1576.
El ejemplo Corpus-de-derecho-castellano-indiano-digital/xml/id1-GL/GLp1t1l1.xml está transcrito de la copia digital disponible en la [Bayerische StaatsBibliothek](http://www.mdz-nbn-resolving.de/urn/resolver.pl?urn=urn:nbn:de:bvb:12-bsb11304365-2). 
Con base en los propósitos de realizar un etiquetado TEI _cercano_ a una edición crítica digital y además incluir otras etiquetas prosopográficas, legales y conceptuales, sería interesante revisar este esquema y de ser necesario proponer modificaciones.

**Comment by vgayolrs** [comment]
Después de una revisión del etiquetado del archivo [GLp1t1l1.xml](https://github.com/Cibercliografia/Corpus-de-derecho-castellano-indiano-digital/blob/master/xml/id1-GL/GLp1t1l1.xml), se puede decir que hay que retrabajar el `<teiHeader>` para lograr un esquema más específico para documento normativo.

He estado trabajando al respecto y una primera propuesta está en el repositorio del proyecto piloto reformado, [CNHID-repo](https://github.com/vgayolrs/CNHID-repo): el archivo [`esquemabasico.xml`](https://github.com/vgayolrs/CNHID-repo/blob/main/texto_xml-tei/esquemaBasico.xml).

Por lo demás, el etiquetado del `<text>` se puede hacer muy sencillo o llegar a detalles mínimos. Sería bueno que se pudiese discutir la más reciente versión del proyecto.

Voy a cerrar, por lo tanto, este  *issue*, pero pero podemos reabrirlo si quieres.
